// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Y1nMjUCoLhf6MrTs8AzRKjcJ62js1Ps',
    appId: '1:917647567038:web:678965bc8758ed728b16ef',
    messagingSenderId: '917647567038',
    projectId: 'chiyou-android',
    authDomain: 'chiyou-android.firebaseapp.com',
    storageBucket: 'chiyou-android.firebasestorage.app',
    measurementId: 'G-FFVNZ8TC41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnVLf286gqyvUkb2-fZAeqI59kEJ8jns',
    appId: '1:917647567038:android:3b83b5dc490c1e1b8b16ef',
    messagingSenderId: '917647567038',
    projectId: 'chiyou-android',
    storageBucket: 'chiyou-android.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClD0uZM2qRQpWs-bguHgu3XB2Z8iKP69s',
    appId: '1:917647567038:ios:22dc5307502c5a338b16ef',
    messagingSenderId: '917647567038',
    projectId: 'chiyou-android',
    storageBucket: 'chiyou-android.firebasestorage.app',
    iosBundleId: 'com.example.chiyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClD0uZM2qRQpWs-bguHgu3XB2Z8iKP69s',
    appId: '1:917647567038:ios:22dc5307502c5a338b16ef',
    messagingSenderId: '917647567038',
    projectId: 'chiyou-android',
    storageBucket: 'chiyou-android.firebasestorage.app',
    iosBundleId: 'com.example.chiyou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Y1nMjUCoLhf6MrTs8AzRKjcJ62js1Ps',
    appId: '1:917647567038:web:5f5bd71746e6ab8f8b16ef',
    messagingSenderId: '917647567038',
    projectId: 'chiyou-android',
    authDomain: 'chiyou-android.firebaseapp.com',
    storageBucket: 'chiyou-android.firebasestorage.app',
    measurementId: 'G-B47L64F3LX',
  );
}
